//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ONVIFPTZControl
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Camera()
        {
            this.CameraFrameTimes = new HashSet<CameraFrameTime>();
        }
    
        public int Id { get; set; }
        public string Url { get; set; }
        public int Port { get; set; }
        public int FrameTimeSec { get; set; }
        public string Usermane { get; set; }
        public string Password { get; set; }
        public int ProjectId { get; set; }
        public Nullable<System.DateTime> NextSendDate { get; set; }
        public string NextSendDWM { get; set; }
        public Nullable<System.DateTime> NextFrameDate { get; set; }
        public System.DateTime CreateDate { get; set; }
        public bool IsDisabled { get; set; }
        public string RtspPort { get; set; }
        public string Name { get; set; }
        public string Presets { get; set; }
        public bool VideoDisabled { get; set; }
    
        public virtual Project Project { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CameraFrameTime> CameraFrameTimes { get; set; }
    }
}
