// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFOnvifAPI.Models;

public partial class CameraFrameTime
{
    public int Id { get; set; }

    public int CameraId { get; set; }

    public string FrameTime { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual Camera Camera { get; set; }
}