// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;

namespace EFOnvifAPI.Models;

public partial class Camera
{
    public int Id { get; set; }

    public string Url { get; set; }

    public int Port { get; set; }

    public int FrameTimeSec { get; set; }

    public string Usermane { get; set; }

    public string Password { get; set; }

    public int ProjectId { get; set; }

    public DateTime? NextSendDate { get; set; }

    public string NextSendDwm { get; set; }

    public DateTime? NextFrameDate { get; set; }

    public DateTime CreateDate { get; set; }

    public bool IsDisabled { get; set; }

    public string RtspPort { get; set; }

    public string Name { get; set; }

    public string Presets { get; set; }

    public bool VideoDisabled { get; set; }

    public virtual ICollection<CameraFrameTime> CameraFrameTimes { get; set; } = new List<CameraFrameTime>();

    public virtual Project Project { get; set; }
}
