// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFOnvifAPI.Models;

public partial class EmailAndWhatsAppSender
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string PhoneNumber { get; set; }

    public string Email { get; set; }

    public int ProjectId { get; set; }

    public DateTime CreateDate { get; set; }

    public bool IsDisabled { get; set; }

    public virtual Project Project { get; set; }
}