// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFOnvifAPI.Models;

public partial class Organization
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public DateTime CreateDate { get; set; }

    public virtual ICollection<Project> Projects { get; set; } = new List<Project>();
}