// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFOnvifAPI.Models;

public partial class Project
{
    public int Id { get; set; }

    public string Name { get; set; }

    public string Type { get; set; }

    public int OrganizationId { get; set; }

    public DateTime CreateDate { get; set; }

    public bool IsDisabled { get; set; }

    public virtual ICollection<Camera> Cameras { get; set; } = new List<Camera>();

    public virtual ICollection<EmailAndWhatsAppSender> EmailAndWhatsAppSenders { get; set; } = new List<EmailAndWhatsAppSender>();

    public virtual Organization Organization { get; set; }
}