// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EFOnvifAPI.Models;

public partial class User
{
    public int Id { get; set; }

    public byte[] PasswordHash { get; set; }

    public string Name { get; set; }

    public DateTime CreateDate { get; set; }

    public bool IsDisabled { get; set; }
}